# Generated by Django 2.2.2 on 2020-05-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
                ('school', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(default='default', max_length=400),
        ),
    ]
