# Generated by Django 2.2.2 on 2020-05-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200512_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
