# Generated by Django 2.2.2 on 2020-05-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200512_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='summary',
            field=models.CharField(default='default', max_length=400),
        ),
    ]
