# Generated by Django 2.2.2 on 2020-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tskills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_title', models.CharField(default='default', max_length=100)),
                ('ts_summary', models.CharField(default='default', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='skills',
            name='ts_summary',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='ts_title',
        ),
    ]
