# Generated by Django 2.2.2 on 2020-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200512_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='tskills',
            name='ts_level_duration',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
