# Generated by Django 2.2.2 on 2020-05-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default='default', max_length=100)),
                ('link', models.CharField(default='default', max_length=300)),
                ('summary', models.CharField(default='default', max_length=500)),
                ('source', models.CharField(default='default', max_length=100)),
            ],
        ),
    ]
