# Generated by Django 2.2.2 on 2020-05-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilefooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
