# Generated by Django 2.2.2 on 2020-05-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(default='default', max_length=300)),
                ('title', models.CharField(default='default', max_length=100)),
                ('link', models.CharField(default='default', max_length=300)),
                ('company', models.CharField(default='default', max_length=100)),
            ],
        ),
    ]
